version: "3.8"

services:
  couchbase:
    image: facetdigital/couchbasefakeit:enterprise-7.0.0-beta
    # build:
    #   context: ../.
    container_name: cbfakeit
    environment:
      - CB_SERVICES=kv,n1ql,index,fts,eventing,cbas
    volumes:
      - "./:/startup"
    ports:
      - "8091-8096:8091-8096"
      - "11207:11207"
      - "11210-11211:11210-11211"
